export const additionalPlayers = [
  { name: 'Shreyas Iyer', role: 'Batsman', country: 'India' },
  { name: 'Ruturaj Gaikwad', role: 'Batsman', country: 'India' },
  { name: 'Yashasvi Jaiswal', role: 'Batsman', country: 'India' },
  { name: 'Ishan Kishan', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Shikhar Dhawan', role: 'Batsman', country: 'India' },
  { name: 'Ajinkya Rahane', role: 'Batsman', country: 'India' },
  { name: 'Manish Pandey', role: 'Batsman', country: 'India' },
  { name: 'Prithvi Shaw', role: 'Batsman', country: 'India' },
  { name: 'Mayank Agarwal', role: 'Batsman', country: 'India' },
  { name: 'Tilak Varma', role: 'Batsman', country: 'India' },
  { name: 'Rinku Singh', role: 'Batsman', country: 'India' },
  { name: 'Sai Sudharsan', role: 'Batsman', country: 'India' },
  { name: 'Devdutt Padikkal', role: 'Batsman', country: 'India' },
  { name: 'Rahul Tripathi', role: 'Batsman', country: 'India' },
  { name: 'Mohammed Siraj', role: 'Bowler', country: 'India' },
  { name: 'Arshdeep Singh', role: 'Bowler', country: 'India' },
  { name: 'Bhuvneshwar Kumar', role: 'Bowler', country: 'India' },
  { name: 'Deepak Chahar', role: 'Bowler', country: 'India' },
  { name: 'Shardul Thakur', role: 'All-Rounder', country: 'India' },
  { name: 'Umesh Yadav', role: 'Bowler', country: 'India' },
  { name: 'Ishant Sharma', role: 'Bowler', country: 'India' },
  { name: 'Mukesh Kumar', role: 'Bowler', country: 'India' },
  { name: 'Avesh Khan', role: 'Bowler', country: 'India' },
  { name: 'Prasidh Krishna', role: 'Bowler', country: 'India' },
  { name: 'Ravi Bishnoi', role: 'Bowler', country: 'India' },
  { name: 'Kuldeep Yadav', role: 'Bowler', country: 'India' },
  { name: 'Washington Sundar', role: 'All-Rounder', country: 'India' },
  { name: 'Axar Patel', role: 'All-Rounder', country: 'India' },
  { name: 'Rahul Chahar', role: 'Bowler', country: 'India' },
  { name: 'Varun Chakaravarthy', role: 'Bowler', country: 'India' },
  { name: 'T Natarajan', role: 'Bowler', country: 'India' },
  { name: 'Mohit Sharma', role: 'Bowler', country: 'India' },
  { name: 'Sandeep Sharma', role: 'Bowler', country: 'India' },
  { name: 'Harshal Patel', role: 'Bowler', country: 'India' },
  { name: 'Krunal Pandya', role: 'All-Rounder', country: 'India' },
  { name: 'Deepak Hooda', role: 'All-Rounder', country: 'India' },
  { name: 'Shivam Dube', role: 'All-Rounder', country: 'India' },
  { name: 'Vijay Shankar', role: 'All-Rounder', country: 'India' },
  { name: 'Riyan Parag', role: 'All-Rounder', country: 'India' },
  { name: 'Venkatesh Iyer', role: 'All-Rounder', country: 'India' },
  { name: 'Dinesh Karthik', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Wriddhiman Saha', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Jitesh Sharma', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Dhruv Jurel', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Kane Williamson', role: 'Batsman', country: 'New Zealand' },
  { name: 'Steve Smith', role: 'Batsman', country: 'Australia' },
  { name: 'Joe Root', role: 'Batsman', country: 'England' },
  { name: 'Harry Brook', role: 'Batsman', country: 'England' },
  { name: 'Travis Head', role: 'Batsman', country: 'Australia' },
  { name: 'Devon Conway', role: 'Batsman', country: 'New Zealand' },
  { name: 'Aiden Markram', role: 'Batsman', country: 'South Africa' },
  { name: 'David Miller', role: 'Batsman', country: 'South Africa' },
  { name: 'Shimron Hetmyer', role: 'Batsman', country: 'West Indies' },
  { name: 'Rovman Powell', role: 'Batsman', country: 'West Indies' },
  { name: 'Jason Roy', role: 'Batsman', country: 'England' },
  { name: 'Jonny Bairstow', role: 'Wicket-Keeper', country: 'England' },
  { name: 'Anrich Nortje', role: 'Bowler', country: 'South Africa' },
  { name: 'Lungi Ngidi', role: 'Bowler', country: 'South Africa' },
  { name: 'Marco Jansen', role: 'All-Rounder', country: 'South Africa' },
  { name: 'Lockie Ferguson', role: 'Bowler', country: 'New Zealand' },
  { name: 'Matt Henry', role: 'Bowler', country: 'New Zealand' },
  { name: 'Tim Southee', role: 'Bowler', country: 'New Zealand' },
  { name: 'Josh Hazlewood', role: 'Bowler', country: 'Australia' },
  { name: 'Adam Zampa', role: 'Bowler', country: 'Australia' },
  { name: 'Adil Rashid', role: 'Bowler', country: 'England' },
  { name: 'Reece Topley', role: 'Bowler', country: 'England' },
  { name: 'Maheesh Theekshana', role: 'Bowler', country: 'Sri Lanka' },
  { name: 'Matheesha Pathirana', role: 'Bowler', country: 'Sri Lanka' },
  { name: 'Mustafizur Rahman', role: 'Bowler', country: 'Bangladesh' },
  { name: 'Alzarri Joseph', role: 'Bowler', country: 'West Indies' },
  { name: 'Naveen-ul-Haq', role: 'Bowler', country: 'Afghanistan' },
  { name: 'Fazalhaq Farooqi', role: 'Bowler', country: 'Afghanistan' },
  { name: 'Marcus Stoinis', role: 'All-Rounder', country: 'Australia' },
  { name: 'Cameron Green', role: 'All-Rounder', country: 'Australia' },
  { name: 'Mitchell Marsh', role: 'All-Rounder', country: 'Australia' },
  { name: 'Liam Livingstone', role: 'All-Rounder', country: 'England' },
  { name: 'Moeen Ali', role: 'All-Rounder', country: 'England' },
  { name: 'Sikandar Raza', role: 'All-Rounder', country: 'Zimbabwe' },
  { name: 'Shakib Al Hasan', role: 'All-Rounder', country: 'Bangladesh' },
  { name: 'Jason Holder', role: 'All-Rounder', country: 'West Indies' },
  { name: 'Kyle Mayers', role: 'All-Rounder', country: 'West Indies' },
  { name: 'Romario Shepherd', role: 'All-Rounder', country: 'West Indies' },
  { name: 'Phil Salt', role: 'Wicket-Keeper', country: 'England' },
  { name: 'Rahmanullah Gurbaz', role: 'Wicket-Keeper', country: 'Afghanistan' },
  { name: 'Matthew Wade', role: 'Wicket-Keeper', country: 'Australia' },
  { name: 'Tristan Stubbs', role: 'Wicket-Keeper', country: 'South Africa' },
  { name: 'Rachin Ravindra', role: 'All-Rounder', country: 'New Zealand' },
  { name: 'Daryl Mitchell', role: 'All-Rounder', country: 'New Zealand' },
  { name: 'Azmatullah Omarzai', role: 'All-Rounder', country: 'Afghanistan' },
  { name: 'Spencer Johnson', role: 'Bowler', country: 'Australia' },
  { name: 'Gerald Coetzee', role: 'Bowler', country: 'South Africa' },
  { name: 'Rilee Rossouw', role: 'Batsman', country: 'South Africa' },
  { name: 'Sherfane Rutherford', role: 'Batsman', country: 'West Indies' },
  { name: 'Shai Hope', role: 'Wicket-Keeper', country: 'West Indies' },
  { name: 'Nandre Burger', role: 'Bowler', country: 'South Africa' },
  { name: 'Tom Kohler-Cadmore', role: 'Batsman', country: 'England' },
  { name: 'Nuwan Thushara', role: 'Bowler', country: 'Sri Lanka' },
  { name: 'Dilshan Madushanka', role: 'Bowler', country: 'Sri Lanka' },
  { name: 'Wanindu Hasaranga', role: 'All-Rounder', country: 'Sri Lanka' },
  { name: 'Rajat Patidar', role: 'Batsman', country: 'India' },
  { name: 'Shahrukh Khan', role: 'All-Rounder', country: 'India' },
  { name: 'Abhinav Manohar', role: 'Batsman', country: 'India' },
  { name: 'Rahul Tewatia', role: 'All-Rounder', country: 'India' },
  { name: 'Ashutosh Sharma', role: 'Batsman', country: 'India' },
  { name: 'Shashank Singh', role: 'Batsman', country: 'India' },
  { name: 'Prabhsimran Singh', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Nitish Reddy', role: 'All-Rounder', country: 'India' },
  { name: 'Abhishek Sharma', role: 'All-Rounder', country: 'India' },
  { name: 'Abdul Samad', role: 'Batsman', country: 'India' },
  { name: 'Mayank Yadav', role: 'Bowler', country: 'India' },
  { name: 'Yash Thakur', role: 'Bowler', country: 'India' },
  { name: 'Navdeep Saini', role: 'Bowler', country: 'India' },
  { name: 'Khaleel Ahmed', role: 'Bowler', country: 'India' },
  { name: 'Chetan Sakariya', role: 'Bowler', country: 'India' },
  { name: 'Jaydev Unadkat', role: 'Bowler', country: 'India' },
  { name: 'Sandeep Warrier', role: 'Bowler', country: 'India' },
  { name: 'Umran Malik', role: 'Bowler', country: 'India' },
  { name: 'Karthik Tyagi', role: 'Bowler', country: 'India' },
  { name: 'Akash Deep', role: 'Bowler', country: 'India' },
  { name: 'Vijaykumar Vyshak', role: 'Bowler', country: 'India' },
  { name: 'Harshit Rana', role: 'Bowler', country: 'India' },
  { name: 'Vaibhav Arora', role: 'Bowler', country: 'India' },
  { name: 'Suyash Sharma', role: 'Bowler', country: 'India' },
  { name: 'Tushar Deshpande', role: 'Bowler', country: 'India' },
  { name: 'Matheesha Pathirana', role: 'Bowler', country: 'Sri Lanka' },
  { name: 'Simarjeet Singh', role: 'Bowler', country: 'India' },
  { name: 'Deepak Chahar', role: 'Bowler', country: 'India' },
  { name: 'Maheesh Theekshana', role: 'Bowler', country: 'Sri Lanka' },
  { name: 'Mustafizur Rahman', role: 'Bowler', country: 'Bangladesh' },
  { name: 'Gudakesh Motie', role: 'Bowler', country: 'West Indies' },
  { name: 'Akeal Hosein', role: 'Bowler', country: 'West Indies' },
  { name: 'Keshav Maharaj', role: 'Bowler', country: 'South Africa' },
  { name: 'Tabraiz Shamsi', role: 'Bowler', country: 'South Africa' },
  { name: 'Ish Sodhi', role: 'Bowler', country: 'New Zealand' },
  { name: 'Mitchell Santner', role: 'All-Rounder', country: 'New Zealand' },
  { name: 'Michael Bracewell', role: 'All-Rounder', country: 'New Zealand' },
  { name: 'Will Jacks', role: 'All-Rounder', country: 'England' },
  { name: 'Naman Dhir', role: 'All-Rounder', country: 'India' },
  { name: 'Nehal Wadhera', role: 'Batsman', country: 'India' },
  { name: 'Piyush Chawla', role: 'Bowler', country: 'India' },
  { name: 'Amit Mishra', role: 'Bowler', country: 'India' },
  { name: 'Praveen Dubey', role: 'Bowler', country: 'India' },
  { name: 'Kuldeep Sen', role: 'Bowler', country: 'India' },
  { name: 'Yudhvir Singh', role: 'Bowler', country: 'India' },
  { name: 'Rasikh Salam', role: 'Bowler', country: 'India' },
  { name: 'Arjun Tendulkar', role: 'Bowler', country: 'India' },
  { name: 'Sanjay Yadav', role: 'All-Rounder', country: 'India' },
  { name: 'Anukul Roy', role: 'All-Rounder', country: 'India' },
  { name: 'Ramandeep Singh', role: 'All-Rounder', country: 'India' },
  { name: 'Lalit Yadav', role: 'All-Rounder', country: 'India' },
  { name: 'Ripal Patel', role: 'All-Rounder', country: 'India' },
  { name: 'Yash Dhull', role: 'Batsman', country: 'India' },
  { name: 'Aryan Juyal', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Upendra Yadav', role: 'Wicket-Keeper', country: 'India' },
  { name: 'KS Bharat', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Narayan Jagadeesan', role: 'Wicket-Keeper', country: 'India' },
  { name: 'Luvnith Sisodia', role: 'Wicket-Keeper', country: 'India' }
];
